# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-31 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0002_auto_20190730_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='image',
        ),
    ]
