# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-09 17:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0007_auto_20190902_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugs',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='bug', to=settings.AUTH_USER_MODEL),
        ),
    ]
